// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Article    string
	ArticleMap string
	User       string
}{
	Article:    "article",
	ArticleMap: "article_map",
	User:       "user",
}
